--- 
- 
  become: true
  handlers: 
    - 
      name: "restart apache"
      service: "name=httpd state=restarted"
  hosts: servers
  tasks: 
    - 
      name: "Install Apache Webserver"
      yum: "pkg=httpd state=latest"
    - 
      copy: "src=index.html dest={{ project_root }}/index.html owner=apache group=apache mode=0644"
      name: "Place the index file at project root"
    - 
      name: "Enable Apache on system reboot"
      notify: "restart apache"
      service: "name=httpd enabled=yes"
  vars: 
    project_root: /var/www/html

